### ISSUE TITLE
Error Log : Please help

### ISSUE THREAD

**Issue by DaggieBlanqx** [Linzaer/Face-Track-Detect-Extract#9]
D:\Practice\scs\lab\facextract>python start.py videos

2019-05-07 21:15:01,587 - MOT - INFO - Start track and extract...... -  MainThread - 6832
2019-05-07 21:15:01.602733: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
WARNING:tensorflow:From C:\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From D:\Practice\scs\lab\facextract\align\detect_face.py:212: calling reduce_max_v1 (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From D:\Practice\scs\lab\facextract\align\detect_face.py:214: calling reduce_sum_v1 (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From D:\Practice\scs\lab\facextract\align\detect_face.py:215: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
Traceback (most recent call last):
  File "start.py", line 147, in <module>
    main()
  File "start.py", line 33, in main
    pnet, rnet, onet = detect_face.create_mtcnn(sess, os.path.join(project_dir, "align"))
  File "D:\Practice\scs\lab\facextract\align\detect_face.py", line 289, in create_mtcnn
    pnet.load(os.path.join(model_path, 'det1.npy'), sess)
  File "D:\Practice\scs\lab\facextract\align\detect_face.py", line 87, in load
    data_dict = np.load(data_path, encoding='latin1').item()  # pylint: disable=no-member
  File "C:\Python36\lib\site-packages\numpy\lib\npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "C:\Python36\lib\site-packages\numpy\lib\format.py", line 692, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

D:\Practice\scs\lab\facextract>

**Comment by 1374207430** [comment]
check you numpy ;update numpy from 1.16.3 to 1.16.2 
good luck

**Comment by Linzaer** [comment]
The problem of numpy version, try 1.16.2.
